#!/usr/bin/env bash

pandoc $currfile -s --to=html5 -o $pandoc/$1.html \
            --mathjax \
            --filter=$pandoc/assets/link2html.py \
            -H $pandoc/assets/header.html \
            -T $prefixtail
