#!/usr/bin/env bash


### convert to pdf with latex
#############################

# pandoc $currfile --to=pdf -o $pandoc/$1.pdf




### convert to html (panflute filter)
#####################################

# pandoc $currfile -s --to=html5 -o $pandoc/$1.html \
#             --mathjax \
#             --filter=$pandoc/assets/link2html.py \
#             -H $pandoc/assets/header.html \
#             -T $prefixtail




### convert to html (lua filter)
################################

pandoc $currfile -s --to=html5 -o $pandoc/$1.html \
            --mathjax \
            --lua-filter=$pandoc/assets/link2html.lua \
            -H $pandoc/assets/header.html \
            -T $prefixtail
