#!/usr/bin/env bash


### convert current note to html (lua filter)
#############################################

# pandoc $currfile -s --to=html5 -o $pandoc/$1.html \
#             --mathjax \
#             --lua-filter=$pandoc/assets/link2html.lua \
#             -H $pandoc/assets/header.html \
#             -A $pandoc/assets/footer.html \
#             -T $prefixtail




### convert all notes to html (lua filter)
##########################################

for note in *.md; do
    [[ $note == "README.md" ]] && continue
    name="${note%.*}"
    pandoc $note -s --to=html5 -o $pandoc/$name.html \
                --mathjax \
                --lua-filter=$pandoc/assets/link2html.lua \
                -H $pandoc/assets/header.html \
                -A $pandoc/assets/footer.html \
                -T $prefixtail
done




### convert current note to pdf (with latex)
############################################

# pandoc $currfile --to=pdf -o $pandoc/$1.pdf




### convert all notes to pdf (with latex)
############################################

# for note in *.md; do
#     [[ $note == "README.md" ]] && continue
#     name="${note%.*}"
#     pandoc $note --to=pdf -o $pandoc/$name.pdf
# done
