#! /usr/bin/env bash

cd ./..
rm index.html
rm config.html
rm notes.html
rm attack.html
rm astro.html
rm mail.html
rm inmyhead.html
rm cellar.html
rm cv.html
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/index.md --mathjax --highlight-style tango -o index.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/config.md  --mathjax --highlight-style tango -o config.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/notes.md --mathjax --highlight-style tango -o notes.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/attack.md  --mathjax --highlight-style tango -o attack.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/astro.md --mathjax --highlight-style tango -o astro.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/mail.md --mathjax --highlight-style tango -o mail.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/inmyhead.md --mathjax --highlight-style tango -o inmyhead.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/cellar.md --mathjax --highlight-style tango -o cellar.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/cv.md --mathjax --highlight-style tango -o cv.html -T Geoteo
