#! /usr/bin/env bash

cd ./..
rm index.html
rm config.html
rm notes.html
rm attack.html
rm astro.html
rm contact.html
rm inmyhead.html
rm cellar.html
rm info.html
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/index.md --mathjax --highlight-style tango -o index.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/config.md  --mathjax --highlight-style tango -o config.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/notes.md --mathjax --highlight-style tango -o notes.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/attack.md  --mathjax --highlight-style tango -o attack.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/astro.md --mathjax --highlight-style tango -o astro.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/contact.md --mathjax --highlight-style tango -o contact.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/inmyhead.md --mathjax --highlight-style tango -o inmyhead.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/cellar.md --mathjax --highlight-style tango -o cellar.html -T Geoteo
pandoc -s -c style.css -H header.html -B prebody.html -A footer.html src/info.md --mathjax --highlight-style tango -o info.html -T Geoteo
